"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from core.base import *
from pathlib import Path
import os, sys, environ, boto3
from django.utils.translation import gettext_lazy as _

AWS_S3 = boto3.resource('s3')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(BASE_DIR)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

environ.Env.read_env('.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Cors
CORS_ORIGIN_WHITELIST = env('CORS_ORIGIN_WHITELIST').split(',')

# CSRF
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS').split(',')

# Allow SSL Header with HTTPS
SECURE_PROXY_SSL_HEADER = env('SECURE_PROXY_SSL_HEADER').split(',')

# Allos dynamic host
ALLOWED_CIDR_NETS =  env('ALLOWED_CIDR_NETS').split(',')

# static files
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

# Locales available path
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale/')
]

INTERNAL_IPS = [
    "127.0.0.1",
]